version: '3.8'

services:
  frontend:
    container_name: react_app
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - ../frontend/node_modules:/app/node_modules  # Maps node_modules correctly
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - backend  # Ensures backend starts first

  backend:
    container_name: fastapi_app
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app  # Mounts the backend folder for live updates
    depends_on:
      - db  # Ensures database starts before backend
    environment:
      - DATABASE_URL=sqlite:///app/milk_tracking.db  # SQLite DB connection path
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    container_name: sqlite_db
    image: alpine
    volumes:
      - sqlite_data:/app/database  # Persistent SQLite storage
    command: tail -f /dev/null  # Keeps container running for persistence

volumes:
  sqlite_data:
